name: Badge Checker
# A workflow to ensure that all badges have been accounted for.

on:
  push:
  schedule:
    - cron: "38 9 * * 0"

jobs:
  get-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            data/*
            !data/Guy_sql
            BadgeChecker/
          sparse-checkout-cone-mode: false

      - name: Cache and setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Test Badges
        run: |
          cd BadgeChecker
          cargo run
